GET http://localhost:4004/v2/odata/v4/catalog/Products

###

GET http://localhost:4004/v2/odata/v4/catalog/Books


###
POST http://localhost:4004/v2/odata/v4/catalog/Books
content-type: application/json

{ 
    "ID": 3,
    "title": "Harry Potter",
    "stock": 250 
}

###
GET http://localhost:4004/v2/odata/v4/catalog/Products(1)

###
POST  http://localhost:4004/v2/odata/v4/catalog/Products(1)/checkPrice()
content-type: application/json 

{
    "units":10
}

###
POST  http://localhost:4004/v2/odata/v4/catalog/Products(1)/order()
content-type: application/json 

{
    "units":10
}

###
POST  https://b752d8e1trial-dev-openshop-srv.cfapps.us10-001.hana.ondemand.com/v2/odata/v4/catalog/Products(1)/order()
content-type: application/json 

{
    "units":2
}

###

GET  https://b752d8e1trial-dev-openshop-srv.cfapps.us10-001.hana.ondemand.com/v2/odata/v4/catalog/Orders?$expand=Products
